- name: Install openjdk Java-11 version
  shell: "amazon-linux-extras install java-openjdk11 -y"

- name: Download hazelcast latest binary
  get_url:
    url: "{{ hc_url_latest }}"
    timeout: 120
    dest: "{{ hc_installation_dir }}"
    mode: 0755

- name: Install hazelcast latest binary
  unarchive:
    src: "{{ hc_installation_dir }}/hazelcast-{{ hc_version }}.tar.gz"
    dest: "{{ hc_installation_dir }}"
    remote_src: yes

- name: Create systemd service file for Hazelcast 
  template:
    dest: "{{ systemd_path }}/hazelcast.service"
    src: "hazelcast.service.j2"

- name: Create systemd service file for Hazelcast-Mancenter 
  template:
    dest: "{{ systemd_path }}/hazelcast_mancenter.service"
    src: "hazelcast_mancenter.service.j2"
  when: inventory_hostname == 'hc1.stageinternal.com'

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
    
#- name: Start the Hazelcast Mancenter Service 
#  service:
###    name: hazelcast_mancenter 
#    state: started
#    enabled: yes
#  when: inventory_hostname == 'hc1.stageinternal.com'

#- name: Start the Hazelcast Service 
#  service:
#    name: hazelcast
#    state: started
#    enabled: yes



